# Generated by Django 5.2.11 on 2026-02-19 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotoboyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnh_number', models.CharField(max_length=20, verbose_name='CNH')),
                ('category', models.CharField(choices=[('TELE', 'Tele-Entrega (Por corrida)'), ('DIARIA', 'Diária'), ('MENSAL', 'Mensal Fixo')], max_length=20)),
                ('vehicle_plate', models.CharField(max_length=10, verbose_name='Placa do Veículo')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponível?')),
                ('active_since', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motoboy_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10, verbose_name='Placa')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca/Modelo')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Cor')),
                ('type', models.CharField(choices=[('MOTO', 'Moto'), ('CARRO', 'Carro'), ('VAN', 'Van')], default='MOTO', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='logistics.motoboyprofile')),
            ],
        ),
    ]
