# Generated by Django 5.2.11 on 2026-02-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motoboyprofile',
            name='category',
            field=models.CharField(choices=[('TELE', 'Tele-Entrega (Tele)'), ('DIARIA', 'Diária'), ('MENSAL', 'Mensal')], max_length=20),
        ),
    ]
