# Generated by Django 5.2.11 on 2026-02-19 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OSDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(max_length=100, verbose_name='Nome Destinatário')),
                ('destination_phone', models.CharField(max_length=20, verbose_name='Telefone Destino')),
                ('destination_street', models.CharField(max_length=255, verbose_name='Rua (Destino)')),
                ('destination_number', models.CharField(max_length=20, verbose_name='Número (Destino)')),
                ('destination_complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento (Destino)')),
                ('destination_district', models.CharField(max_length=100, verbose_name='Bairro (Destino)')),
                ('destination_city', models.CharField(max_length=100, verbose_name='Cidade (Destino)')),
                ('destination_zip_code', models.CharField(max_length=10, verbose_name='CEP (Destino)')),
                ('destination_reference', models.CharField(blank=True, max_length=255, verbose_name='Ponto de Referência (Destino)')),
                ('destination_notes', models.TextField(blank=True, verbose_name='Observações')),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Entrega Real')),
                ('geo_delivery_lat', models.CharField(blank=True, max_length=50, verbose_name='Geo Entrega (Lat)')),
                ('geo_delivery_lng', models.CharField(blank=True, max_length=50, verbose_name='Geo Entrega (Lng)')),
                ('proof_photo', models.ImageField(blank=True, null=True, upload_to='proofs/', verbose_name='Foto Comprovação')),
                ('receiver_name', models.CharField(blank=True, max_length=100, verbose_name='Nome de quem recebeu')),
                ('receiver_signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Assinatura Digital')),
                ('confirmation_code', models.CharField(blank=True, max_length=6, verbose_name='Código OTP')),
            ],
        ),
        migrations.CreateModel(
            name='OSItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição do Item')),
                ('total_quantity', models.PositiveIntegerField(verbose_name='Quantidade Total')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso (kg)')),
                ('dimensions', models.CharField(blank=True, max_length=50, verbose_name='Dimensões (CxLxA)')),
                ('declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Declarado')),
                ('is_fragile', models.BooleanField(default=False, verbose_name='Frágil?')),
                ('requires_signature', models.BooleanField(default=True, verbose_name='Exige Assinatura?')),
                ('item_notes', models.TextField(blank=True, verbose_name='Observações do Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_allocated', models.PositiveIntegerField(verbose_name='Qtd Alocada para este destino')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributed_items', to='orders.osdestination')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='orders.ositem')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número da OS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente'), ('AGENDADA', 'Agendada')], default='NORMAL', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITO', 'Aceito pelo Motoboy'), ('COLETADO', 'Coletado / Em Trânsito'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status Atual')),
                ('requester_name', models.CharField(max_length=100, verbose_name='Nome do Solicitante')),
                ('requester_phone', models.CharField(max_length=20, verbose_name='Telefone do Solicitante')),
                ('vehicle_type', models.CharField(choices=[('MOTO', 'Moto'), ('CARRO', 'Carro'), ('UTILITARIO', 'Utilitário')], default='MOTO', max_length=20)),
                ('payment_method', models.CharField(choices=[('FATURADO', 'Faturado/Empresa'), ('DESTINATARIO', 'Cobrar Destinatário')], default='FATURADO', max_length=20)),
                ('internal_code', models.CharField(blank=True, max_length=50, verbose_name='Código Interno / Centro de Custo')),
                ('is_exclusive_service', models.BooleanField(default=False, verbose_name='Serviço Exclusivo (+ Taxa)')),
                ('requires_return', models.BooleanField(default=False, verbose_name='Adicionar Retorno')),
                ('origin_name', models.CharField(max_length=100, verbose_name='Nome na Coleta')),
                ('origin_responsible', models.CharField(max_length=100, verbose_name='Responsável Coleta')),
                ('origin_phone', models.CharField(max_length=20, verbose_name='Telefone Coleta')),
                ('origin_street', models.CharField(max_length=255, verbose_name='Rua (Coleta)')),
                ('origin_number', models.CharField(max_length=20, verbose_name='Número (Coleta)')),
                ('origin_complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento (Coleta)')),
                ('origin_district', models.CharField(max_length=100, verbose_name='Bairro (Coleta)')),
                ('origin_city', models.CharField(max_length=100, verbose_name='Cidade (Coleta)')),
                ('origin_zip_code', models.CharField(max_length=10, verbose_name='CEP (Coleta)')),
                ('origin_reference', models.CharField(blank=True, max_length=255, verbose_name='Ponto de Referência (Coleta)')),
                ('origin_notes', models.TextField(blank=True, verbose_name='Observações da Coleta')),
                ('expected_pickup', models.DateTimeField(blank=True, null=True, verbose_name='Previsão de Coleta')),
                ('expected_delivery', models.DateTimeField(blank=True, null=True, verbose_name='Previsão de Entrega (Geral)')),
                ('time_window', models.CharField(blank=True, max_length=100, verbose_name='Janela de Horário')),
                ('operational_notes', models.TextField(blank=True, verbose_name='Observações Gerais / Operacionais')),
                ('collected_at', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Coleta Real')),
                ('geo_pickup_lat', models.CharField(blank=True, max_length=50, verbose_name='Geo Coleta (Lat)')),
                ('geo_pickup_lng', models.CharField(blank=True, max_length=50, verbose_name='Geo Coleta (Lng)')),
                ('is_multiple_delivery', models.BooleanField(default=False, editable=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Empresa Solicitante')),
                ('motoboy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='logistics.motoboyprofile', verbose_name='Motoboy Responsável')),
            ],
        ),
        migrations.AddField(
            model_name='ositem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.serviceorder'),
        ),
        migrations.AddField(
            model_name='osdestination',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='orders.serviceorder'),
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(max_length=50)),
                ('status_novo', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='orders.serviceorder')),
            ],
        ),
    ]
