# Generated by Django 5.2.11 on 2026-02-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='osdestination',
            name='destination_state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF (Destino)'),
        ),
        migrations.AddField(
            model_name='ositem',
            name='item_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Item'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='company_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ Solicitante'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Solicitante'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Entrega'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='origin_state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF (Coleta)'),
        ),
    ]
