# Generated by Django 5.2.11 on 2026-02-24 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        ('orders', '0002_osdestination_destination_state_ositem_item_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('COLETA', 'Coleta na Origem'), ('ENTREGA', 'Entrega no Destino')], max_length=20)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.osdestination')),
                ('motoboy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='logistics.motoboyprofile')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='orders.serviceorder')),
            ],
            options={
                'ordering': ['motoboy', 'sequence'],
            },
        ),
    ]
