# Generated by Django 5.2.11 on 2026-02-26 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_routestop'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='parent_os',
            field=models.ForeignKey(blank=True, help_text="Se esta OS foi mesclada dentro de outra, a 'Mãe' aparecerá aqui.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_orders', to='orders.serviceorder'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('AGRUPADO', 'Agrupado'), ('ACEITO', 'Aceito pelo Motoboy'), ('COLETADO', 'Coletado / Em Trânsito'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status Atual'),
        ),
    ]
