# Generated by Django 5.2.11 on 2026-02-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_serviceorder_parent_os_alter_serviceorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('AGRUPADO', 'Agrupado'), ('ACEITO', 'Aceito pelo Motoboy'), ('COLETADO', 'Coletado / Em Trânsito'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado'), ('OCORRENCIA', 'Ocorrência / Problema')], default='PENDENTE', max_length=20, verbose_name='Status Atual'),
        ),
    ]
